# Generated by Django 5.0.2 on 2024-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_cart_order_product_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product_image.jpg', upload_to='product_images/'),
        ),
    ]
